<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="power" nsURI="http://www.fzi.de/Power/1.0" nsPrefix="de.fzi">
  <eSubpackages name="util" nsURI="http://www.fzi.de/Power/Util/1.0" nsPrefix="de.fzi.power">
    <eClassifiers xsi:type="ecore:EDataType" name="Power" instanceClassName="javax.measure.quantity.Power"/>
    <eClassifiers xsi:type="ecore:EClass" name="Entity" abstract="true" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier #//util/NamedElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Dimensionless" instanceClassName="javax.measure.quantity.Dimensionless"/>
  </eSubpackages>
  <eSubpackages name="state" nsURI="http://www.fzi.de/Power/State/1.0" nsPrefix="de.fzi.power">
    <eClassifiers xsi:type="ecore:EClass" name="PowerStateRepository" eSuperTypes="#//util/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerStateMachines" upperBound="-1"
          eType="#//state/PowerStateMachine" containment="true" eOpposite="#//state/PowerStateMachine/powerStateRepository"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractPowerState" abstract="true"
        eSuperTypes="#//util/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerStateMachine" eType="#//state/PowerStateMachine"
          eOpposite="#//state/PowerStateMachine/powerStates"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransitionState" eSuperTypes="#//state/AbstractPowerState">
      <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" lowerBound="1"
          eType="#//state/PowerState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" lowerBound="1"
          eType="#//state/PowerState"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerState" eSuperTypes="#//state/AbstractPowerState"/>
    <eClassifiers xsi:type="ecore:EClass" name="PowerStateMachine" eSuperTypes="#//util/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerStateRepository"
          eType="#//state/PowerStateRepository" eOpposite="#//state/PowerStateRepository/powerStateMachines"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerStates" lowerBound="1"
          upperBound="-1" eType="#//state/AbstractPowerState" containment="true" eOpposite="#//state/AbstractPowerState/powerStateMachine"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="specification" nsURI="http://www.fzi.de/Power/Specification/1.0"
      nsPrefix="de.fzi.power">
    <eClassifiers xsi:type="ecore:EClass" name="PowerModelRepository" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerModelSpecifications"
          upperBound="-1" eType="#//specification/PowerModelSpecification" containment="true"
          eOpposite="#//specification/PowerModelSpecification/powermodelrepository"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerModelSpecification" abstract="true"
        eSuperTypes="#//util/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powermodelrepository"
          eType="#//specification/PowerModelRepository" eOpposite="#//specification/PowerModelRepository/powerModelSpecifications"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="consumptionFactors" upperBound="-1"
          eType="#//specification/ConsumptionFactor" containment="true" eOpposite="#//specification/ConsumptionFactor/powerModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourcePowerModelSpecification" abstract="true"
        eSuperTypes="#//specification/PowerModelSpecification"/>
    <eClassifiers xsi:type="ecore:EClass" name="DistributionPowerModelSpecification"
        abstract="true" eSuperTypes="#//specification/PowerModelSpecification"/>
    <eClassifiers xsi:type="ecore:EClass" name="FixedFactor" eSuperTypes="#//specification/ConsumptionFactor"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConsumptionFactor" abstract="true"
        eSuperTypes="#//util/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerModel" eType="#//specification/PowerModelSpecification"
          eOpposite="#//specification/PowerModelSpecification/consumptionFactors"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MeasuredFactor" eSuperTypes="#//specification/ConsumptionFactor">
      <eStructuralFeatures xsi:type="ecore:EReference" name="metricType" lowerBound="1"
          eType="ecore:EClass ../../org.palladiosimulator.metricspec/model/metricspec.ecore#//NumericalBaseMetricDescription"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeclarativePowerModelSpecification"
        eSuperTypes="#//specification/PowerModelSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="functionalExpression"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeclarativeResourcePowerModelSpecification"
        eSuperTypes="#//specification/DeclarativePowerModelSpecification #//specification/ResourcePowerModelSpecification"/>
    <eClassifiers xsi:type="ecore:EClass" name="DeclarativeDistributionPowerModelSpecification"
        eSuperTypes="#//specification/DeclarativePowerModelSpecification #//specification/DistributionPowerModelSpecification"/>
    <eClassifiers xsi:type="ecore:EClass" name="BlackBoxPowerModelSpecification" abstract="true"
        eSuperTypes="#//specification/PowerModelSpecification"/>
    <eClassifiers xsi:type="ecore:EClass" name="BlackBoxDistributionPowerModelSpecification"
        eSuperTypes="#//specification/DistributionPowerModelSpecification"/>
    <eClassifiers xsi:type="ecore:EClass" name="BlackBoxResourcePowerModelSpecification"
        eSuperTypes="#//specification/ResourcePowerModelSpecification"/>
  </eSubpackages>
  <eSubpackages name="binding" nsURI="http://www.fzi.de/Power/Binding/1.0" nsPrefix="de.fzi.power">
    <eClassifiers xsi:type="ecore:EClass" name="FixedFactorValuePower">
      <eGenericSuperTypes eClassifier="#//binding/AbstractFixedFactorValue">
        <eTypeArguments eClassifier="#//util/Power"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerBindingRepository" eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerBindings" upperBound="-1"
          eType="#//binding/PowerBinding" containment="true" eOpposite="#//binding/PowerBinding/powerBindingRepository"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerBinding" abstract="true" eSuperTypes="#//util/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerBindingRepository"
          eType="#//binding/PowerBindingRepository" eOpposite="#//binding/PowerBindingRepository/powerBindings"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ResourcePowerBinding" eSuperTypes="#//binding/PowerFactorBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourcePowerModelSpecification"
          lowerBound="1" eType="#//specification/ResourcePowerModelSpecification"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DistributionPowerBinding" eSuperTypes="#//binding/PowerFactorBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="distributionPowerModel"
          lowerBound="1" eType="#//specification/DistributionPowerModelSpecification"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerFactorBinding" abstract="true"
        eSuperTypes="#//binding/PowerBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="fixedFactorValues" upperBound="-1"
          containment="true" eOpposite="#//binding/AbstractFixedFactorValue/powerBinding">
        <eGenericType eClassifier="#//binding/AbstractFixedFactorValue">
          <eTypeArguments/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractFixedFactorValue" abstract="true"
        eSuperTypes="platform:/plugin/de.uka.ipd.sdq.identifier/model/identifier.ecore#//Identifier">
      <eTypeParameters name="Q">
        <eBounds eClassifier="ecore:EClass ../../org.palladiosimulator.metricspec/model/metricspec.ecore#//IJSQuantity"/>
      </eTypeParameters>
      <eStructuralFeatures xsi:type="ecore:EReference" name="boundFactor" lowerBound="1"
          eType="#//specification/FixedFactor"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value">
        <eGenericType eClassifier="ecore:EDataType ../../org.palladiosimulator.edp2/model/EDP2.ecore#//ExperimentData/EJSMeasure">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDoubleObject"/>
          <eTypeArguments eTypeParameter="#//binding/AbstractFixedFactorValue/Q"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerBinding" eType="#//binding/PowerFactorBinding"
          eOpposite="#//binding/PowerFactorBinding/fixedFactorValues"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="FixedFactorValueDimensionless">
      <eGenericSuperTypes eClassifier="#//binding/AbstractFixedFactorValue">
        <eTypeArguments eClassifier="#//util/Dimensionless"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConsumptionBehavior" eSuperTypes="#//util/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerCurve" lowerBound="1"
          eType="ecore:EClass platform:/plugin/tools.descartes.dlim.generator/src/tools/descartes/dlim/model/dlim.ecore#//Sequence"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1">
        <eGenericType eClassifier="ecore:EDataType ../../org.palladiosimulator.metricspec/model/metricspec.ecore#//EJSUnit">
          <eTypeArguments eClassifier="#//util/Power"/>
        </eGenericType>
      </eStructuralFeatures>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StatefulResourcePowerBinding" eSuperTypes="#//binding/PowerBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerStateBindings" lowerBound="1"
          upperBound="-1" eType="#//binding/AbstractPowerStateBinding" containment="true"
          eOpposite="#//binding/AbstractPowerStateBinding/statefulResourcePowerBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractPowerStateBinding" abstract="true"
        eSuperTypes="#//util/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="statefulResourcePowerBinding"
          eType="#//binding/StatefulResourcePowerBinding" eOpposite="#//binding/StatefulResourcePowerBinding/powerStateBindings"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerStateBinding" eSuperTypes="#//binding/AbstractPowerStateBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerState" lowerBound="1"
          eType="#//state/PowerState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="binding" lowerBound="1"
          eType="#//binding/ResourcePowerBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TransitionStateBinding" eSuperTypes="#//binding/AbstractPowerStateBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitionState" lowerBound="1"
          eType="#//state/TransitionState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitionConsumption"
          lowerBound="1" eType="#//binding/ConsumptionBehavior" containment="true"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="infrastructure" nsURI="http://www.fzi.de/Power/Infrastructure/1.0"
      nsPrefix="de.fzi.power">
    <eClassifiers xsi:type="ecore:EClass" name="PowerDistributionUnit" eSuperTypes="#//infrastructure/PowerConsumingProvidingEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="PowerConsumingProvidingEntity" abstract="true"
        eSuperTypes="#//infrastructure/PowerConsumingEntity #//infrastructure/PowerProvidingEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="PowerProvidingEntity" abstract="true"
        eSuperTypes="#//util/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="nestedPowerConsumingEntities"
          ordered="false" upperBound="-1" eType="#//infrastructure/PowerConsumingEntity"
          containment="true" eOpposite="#//infrastructure/PowerConsumingEntity/powerProvidingEntity"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="suppliablePeakPower"
          ordered="false" defaultValueLiteral="">
        <eGenericType eClassifier="ecore:EDataType ../../org.palladiosimulator.edp2/model/EDP2.ecore#//ExperimentData/EJSMeasure">
          <eTypeArguments/>
          <eTypeArguments eClassifier="#//util/Power"/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerInfrastructureModel"
          eType="#//infrastructure/PowerInfrastructureRepository" eOpposite="#//infrastructure/PowerInfrastructureRepository/containedPowerProvidingEntities"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="distributionPowerAssemblyContext"
          eType="#//binding/DistributionPowerBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerConsumingEntity" abstract="true"
        eSuperTypes="#//util/Entity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerProvidingEntity"
          ordered="false" eType="#//infrastructure/PowerProvidingEntity" eOpposite="#//infrastructure/PowerProvidingEntity/nestedPowerConsumingEntities"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MountedPowerDistributionUnit" eSuperTypes="#//infrastructure/PowerDistributionUnit">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourceContainer" ordered="false"
          lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ResourceContainer"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractPowerConsumingResource" abstract="true"
        eSuperTypes="#//infrastructure/PowerConsumingEntity">
      <eStructuralFeatures xsi:type="ecore:EReference" name="processingResourceSpecification"
          ordered="false" lowerBound="1" eType="ecore:EClass ../../org.palladiosimulator.pcm/model/pcm.ecore#//resourceenvironment/ProcessingResourceSpecification"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerInfrastructureRepository">
      <eStructuralFeatures xsi:type="ecore:EReference" name="containedPowerProvidingEntities"
          upperBound="-1" eType="#//infrastructure/PowerProvidingEntity" containment="true"
          eOpposite="#//infrastructure/PowerProvidingEntity/powerInfrastructureModel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StatefulPowerConsumingResource" eSuperTypes="#//infrastructure/AbstractPowerConsumingResource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="powerState" lowerBound="1"
          eType="#//binding/AbstractPowerStateBinding"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="statefulResourcePowerBinding"
          lowerBound="1" eType="#//binding/StatefulResourcePowerBinding"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PowerConsumingResource" eSuperTypes="#//infrastructure/AbstractPowerConsumingResource">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resourcePowerAssemblyContext"
          eType="#//binding/ResourcePowerBinding"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
